### ISSUE TITLE
Erro ao gerar PDF

### ISSUE THREAD

**Issue by nmuianga** [alexandreaquiles/solid-na-pratica#2]
Viva @alexandreaquiles quando executo o comando para gerar pdf recebo a seguinte mensagem no terminal: **Erro ao criar arquivo PDF: /home/nmuianga/Desktop/book.pdf** , no entanto, o pdf é gerado mas dá erro ao tentar abrir o mesmo.

**Comment by alexandreaquiles** [comment]
Opa, Nivaldo!

Roda com a opção -v que você verá o stack trace. Aí você manda por aqui?

Em qua., 1 de nov. de 2023 19:35, Nilvandro Muianga <
***@***.***> escreveu:

**Comment by nmuianga** [comment]
Viva @alexandreaquiles, desculpas por voltar depois de muito tempo, ao gerar a versao pdf do livro, foi lancada a seguinte exception:

Erro ao criar arquivo PDF: /home/nmuianga/workspace/java/java/desbravando-solid/solid-na-pratica/book.pdf
java.lang.IllegalStateException: Erro ao criar arquivo PDF: /home/nmuianga/workspace/java/java/desbravando-solid/solid-na-pratica/book.pdf
	at cotuba.Main.main(Main.java:174)
Caused by: com.itextpdf.kernel.PdfException: Document has no pages.
	at com.itextpdf.kernel.pdf.PdfPagesTree.generateTree(PdfPagesTree.java:260)
	at com.itextpdf.kernel.pdf.PdfDocument.close(PdfDocument.java:835)
	at com.itextpdf.layout.Document.close(Document.java:120)
	at cotuba.Main.main(Main.java:173)
	Suppressed: com.itextpdf.kernel.PdfException: Document has no pages.
		at com.itextpdf.kernel.pdf.PdfPagesTree.generateTree(PdfPagesTree.java:260)
		at com.itextpdf.kernel.pdf.PdfDocument.close(PdfDocument.java:835)
		at cotuba.Main.main(Main.java:120)
		
Depois de assistir ao video da aula, e seguido as instrucoes para a execucao da aplicacao a partir do IDE consegui gerar o ebook no formato PDF.

**Comment by alexandreaquiles** [comment]
Sem problemas, @nmuianga!

Cara, pelo stack trace, parece que você esqueceu algum código no GeradorPDF.

O PDF está sendo gerado sem nenhuma página.

Uma outra hipótese é que faltou adicionar o HTML do capítulo na lista de capítulos.

Veja se é alguma dessas coisas!
